version: "3"
services:
  postgresqldb:
    image: postgres:latest
    volumes:
        - /path/to/postgresql-persistence:/bitnami/postgresql
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fas_db
